// Code generated by "stringer -type=Status"; DO NOT EDIT.

package container

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Created-1]
	_ = x[Running-2]
	_ = x[Paused-3]
	_ = x[Restarting-4]
	_ = x[Removing-5]
	_ = x[Exited-6]
	_ = x[Dead-7]
}

const _Status_name = "CreatedRunningPausedRestartingRemovingExitedDead"

var _Status_index = [...]uint8{0, 7, 14, 20, 30, 38, 44, 48}

func (i Status) String() string {
	i -= 1
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
