// Code generated by "stringer -type=Status"; DO NOT EDIT.

package container

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Created-1]
	_ = x[Running-2]
	_ = x[Paused-3]
	_ = x[UnPaused-4]
	_ = x[Stopped-5]
	_ = x[Removed-6]
}

const _Status_name = "CreatedRunningPausedUnPausedStoppedRemoved"

var _Status_index = [...]uint8{0, 7, 14, 20, 28, 35, 42}

func (i Status) String() string {
	i -= 1
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
